### PR TITLE
V2 new docs structure

### PR DESCRIPTION
**Pull request by AleksandarPetrov**

### CODE REVIEW

**Comment by afdaniele** [comment]
@AleksandarPetrov I guess we don't need this anymore

**Comment by liampaull** [comment]
@afdaniele can you close then?

**Comment by afdaniele** [comment]
@liampaull , still waiting for @AleksandarPetrov to make sure he does not need anything from this.

**Comment by AleksandarPetrov** [comment]
Yeah, let's close this one, and I will open a new one with the updated structure.

**Pull request closed without merging**
